ALTER TABLE documents ADD COLUMN IF NOT EXISTS pipeline_phase TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS translated_count INTEGER DEFAULT 0;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS total_count INTEGER DEFAULT 0;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS error_detail JSONB;
